# Generated by Django 2.2.3 on 2019-10-13 19:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 13, 19, 38, 26, 552026, tzinfo=utc)),
        ),
    ]
