# Generated by Django 2.2.3 on 2019-11-05 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20191105_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='oga',
            field=models.FileField(null=True, upload_to='music/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 13, 51, 9, 305770, tzinfo=utc)),
        ),
    ]
