# Generated by Django 2.2.3 on 2019-09-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190914_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(blank=True, max_length=255, upload_to='pictures/%Y/%m/%d/'),
        ),
    ]
